### ISSUE TITLE
Remove akvdotnet Project for it using the old keyvault SDK

### ISSUE THREAD

**Issue by tzhanl** [Azure-Samples/key-vault-dotnet-core-quickstart#13]
Project key-vault-console-app using new Keyvault SDK. Suggest to remove akvdotnet as it using the old keyvault sdk.

**Comment by jongio** [comment]
@msmbaldwin - We are trying to remove all code that references the old SDKs.  Any chance you can either remove the akvdotnet app or updated it heavily to tell the user to not use it?  Thanks, Jon

**Comment by tzhanl** [comment]
PR https://github.com/Azure-Samples/key-vault-dotnet-core-quickstart/pull/14 for this.

**Comment by v-xuto** [comment]
@jongio PR #14 for this issue, and it has been merged. Could we close this issue now? If so, please help close it, because I don't have permission.
